version: '3.4'

services:
  mediporta.stackoverflowwebapi:
    image: ${DOCKER_REGISTRY-}mediportastackoverflowwebapi
    build:
      context: .
      dockerfile: Mediporta.StackOverflowWebAPI/Dockerfile
    depends_on:
        - redis 
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      SOWebApi-network:
        ipv4_address: 172.28.1.1

  redis:
    container_name: Redis
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      SOWebApi-network:
        ipv4_address: 172.28.1.2
    volumes: 
      - cache-data:/data

volumes:
  cache-data:
  
networks:
    SOWebApi-network:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16